@startuml
hide empty description

state Opening : handState = Open
state Opening : statoMano = Aperto
state Closing : handState = Grab

[*] -down-> Opening

Opening -down-> Closing : azzardo==vero
Opening -down-> Fake : azzardo==false

BlockOpen -up-> Opening : hazard==false

@enduml
