name: PlantUML-StateDiagram-to-cpp

services:
  env:
    container_name: env
    image: "eclipse-temurin:17-alpine"
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity

  linux-builder:
    container_name: linux
    image: "eclipse-temurin:17-alpine"
    volumes:
      - .:/app
    working_dir: /app
    command: ./gradlew createReleaseLinux
